# Generated by Django 3.0.3 on 2020-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
