# Generated by Django 3.0.3 on 2020-02-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200205_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
